#!/usr/bin/env python

ROOT = "https://effect-ts.github.io/effect"


def resolve(path: list[str]):
    if len(path) == 2:
        package, member = path
    else:
        package = "effect"
        member = path[-1]

    items = member.split(".")
    module = items[0]
    url = f"{ROOT}/{package}/{module}.ts.html"
    if len(items) >= 2:
        function = items[1]
        url += f"#{function.lower()}"
    return url


if __name__ == "__main__":
    import sys

    print(resolve(sys.argv[1:]))
