#!/usr/bin/env python
import os

# ~/dev/new-machine/zshrc/local-overrides
ORG = os.environ.get("GITHUB_ORG", "fredcollman")


def format_query(query_terms):
    joined = "+".join([f"org%3A{ORG}", *query_terms])
    return f"https://github.com/search?q={joined}&type=Code"


if __name__ == "__main__":
    import sys

    query_terms = sys.argv[1:]
    print(format_query(query_terms))
