#!/usr/bin/env sh
# ~/dev/new-machine/zshrc/local-overrides
if [ -z "${GITHUB_ORG}" ]; then
  GITHUB_ORG=fredcollman
fi

if [ $# -gt 0 ]; then
    echo "https://github.com/$GITHUB_ORG/$1"
else
    echo "https://github.com/$GITHUB_ORG"
fi
