#!/usr/bin/env python


def format_query(author):
    return "https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+author%3A{}+sort%3Aupdated-desc+".format(author)


if __name__ == "__main__":
    import sys
    author = sys.argv[1]
    print(format_query(author))
