#!/usr/bin/env sh

# ~/dev/new-machine/zshrc/local-overrides
if [ -z "${GITHUB_ORG}" ]; then
  GITHUB_ORG=fredcollman
fi

REPO=$1

if [ $# -gt 1 ]; then
    echo "https://github.com/${GITHUB_ORG}/${REPO}/pull/${2}"
else
    echo "https://github.com/${GITHUB_ORG}/${REPO}/pulls"
fi

