#!/usr/bin/env sh
case $1 in
	drf)
		echo "https://github.com/encode/django-rest-framework"
		;;
	dj|django)
		echo "https://github.com/django/django"
		;;
	swag|swagger)
		echo "https://github.com/swagger-api/swagger-ui"
		;;
	sentry)
		echo "https://github.com/getsentry/sentry-python/"
		;;
	jwt|simplejwt)
		echo "https://github.com/davesque/django-rest-framework-simplejwt"
		;;
	configurations|conf)
		echo "https://github.com/jazzband/django-configurations"
		;;
	cra|create-react-app)
		echo "https://github.com/facebook/create-react-app"
		;;
	cy|cyp|cypress)
		echo "https://github.com/cypress-io/cypress"
		;;
	storybook)
		echo "https://github.com/storybookjs/storybook"
		;;
	react-router|router|rr)
		echo "https://github.com/ReactTraining/react-router"
		;;
  effect|eff)
    echo "https://github.com/Effect-TS/effect/tree/main/packages/effect/src"
    ;;
  smol|effect4|eff4)
    echo "https://github.com/Effect-TS/effect-smol/tree/main/packages/effect/src"
    ;;
  sv|svelte)
    echo "https://github.com/sveltejs/svelte/tree/main/packages/svelte/src"
    ;;
  sveltekit|svelte-kit|kit|sk)
    echo "https://github.com/sveltejs/kit/packages/kit/src"
    ;;
  wa|webawesome)
    echo "https://github.com/shoelace-style/webawesome/tree/next/packages/webawesome/src/components"
    ;;
  sl|shoelace)
    echo "https://github.com/shoelace-style/shoelace/tree/next/src/components"
    ;;
  bits|bits-ui)
    echo "https://github.com/huntabyte/bits-ui/tree/main/packages/bits-ui/src/lib/bits"
    ;;
  in|internotes)
    echo "https://github.com/internotes-app/internotes"
    ;;
esac
